# Generated by Django 5.1.2 on 2024-10-18 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notestaking',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
