# Generated by Django 5.1.2 on 2024-10-18 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0002_notestaking_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notestaking',
            name='created_at',
        ),
    ]
