# Generated by Django 5.1.2 on 2024-10-18 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0003_remove_notestaking_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='notestaking',
            name='modified_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
