# Generated by Django 5.1.2 on 2024-10-18 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0004_notestaking_modified_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notestaking',
            name='modified_date',
            field=models.DateTimeField(),
        ),
    ]
